require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  NewCops: enable
  Exclude:
    - ext/**/*
    - vendor/bundle/**/*
Layout/LineLength:
  Max: 140
Style/StringLiterals:
  EnforcedStyle: double_quotes

